//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18010
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleSkeletonServer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleSkeletonServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Initializing Kinect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Kinect is attached to a USB port that does not have sufficient bandwidth to support the camera. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InsufficientBandwidth {
            get {
                return ResourceManager.GetString("InsufficientBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Another application is using the Kinect. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KinectAppConflict {
            get {
                return ResourceManager.GetString("KinectAppConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attach Kinect to PC to play. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoKinectError {
            get {
                return ResourceManager.GetString("NoKinectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kinect is attached to PC, but AC power is missing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoPowerError {
            get {
                return ResourceManager.GetString("NoPowerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One or more of the Speech prerequisites has not been installed.  Please consult the README for more information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoSpeechError {
            get {
                return ResourceManager.GetString("NoSpeechError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kinect is attached to PC, but an error occured, so it isn&apos;t ready. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotReady {
            get {
                return ResourceManager.GetString("NotReady", resourceCulture);
            }
        }
    }
}
