/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package jp.digitalmuseum.kinect;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Frame implements org.apache.thrift.TBase<Frame, Frame._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Frame");

  private static final org.apache.thrift.protocol.TField FRAME_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("frameId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField IMAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("image", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField DEPTH_IMAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("depthImage", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField POSITION_FIELD_DESC = new org.apache.thrift.protocol.TField("position", org.apache.thrift.protocol.TType.STRUCT, (short)4);
  private static final org.apache.thrift.protocol.TField JOINTS_FIELD_DESC = new org.apache.thrift.protocol.TField("joints", org.apache.thrift.protocol.TType.MAP, (short)5);
  private static final org.apache.thrift.protocol.TField WORDS_FIELD_DESC = new org.apache.thrift.protocol.TField("words", org.apache.thrift.protocol.TType.SET, (short)6);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FrameStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FrameTupleSchemeFactory());
  }

  public int frameId; // required
  public ByteBuffer image; // optional
  public ByteBuffer depthImage; // optional
  public Position3D position; // optional
  public Map<JointType,Joint> joints; // required
  public Set<String> words; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FRAME_ID((short)1, "frameId"),
    IMAGE((short)2, "image"),
    DEPTH_IMAGE((short)3, "depthImage"),
    POSITION((short)4, "position"),
    JOINTS((short)5, "joints"),
    WORDS((short)6, "words");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FRAME_ID
          return FRAME_ID;
        case 2: // IMAGE
          return IMAGE;
        case 3: // DEPTH_IMAGE
          return DEPTH_IMAGE;
        case 4: // POSITION
          return POSITION;
        case 5: // JOINTS
          return JOINTS;
        case 6: // WORDS
          return WORDS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __FRAMEID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.IMAGE,_Fields.DEPTH_IMAGE,_Fields.POSITION,_Fields.WORDS};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FRAME_ID, new org.apache.thrift.meta_data.FieldMetaData("frameId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.IMAGE, new org.apache.thrift.meta_data.FieldMetaData("image", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.DEPTH_IMAGE, new org.apache.thrift.meta_data.FieldMetaData("depthImage", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.POSITION, new org.apache.thrift.meta_data.FieldMetaData("position", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Position3D.class)));
    tmpMap.put(_Fields.JOINTS, new org.apache.thrift.meta_data.FieldMetaData("joints", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, JointType.class), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Joint.class))));
    tmpMap.put(_Fields.WORDS, new org.apache.thrift.meta_data.FieldMetaData("words", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Frame.class, metaDataMap);
  }

  public Frame() {
  }

  public Frame(
    int frameId,
    Map<JointType,Joint> joints)
  {
    this();
    this.frameId = frameId;
    setFrameIdIsSet(true);
    this.joints = joints;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Frame(Frame other) {
    __isset_bitfield = other.__isset_bitfield;
    this.frameId = other.frameId;
    if (other.isSetImage()) {
      this.image = org.apache.thrift.TBaseHelper.copyBinary(other.image);
;
    }
    if (other.isSetDepthImage()) {
      this.depthImage = org.apache.thrift.TBaseHelper.copyBinary(other.depthImage);
;
    }
    if (other.isSetPosition()) {
      this.position = new Position3D(other.position);
    }
    if (other.isSetJoints()) {
      Map<JointType,Joint> __this__joints = new HashMap<JointType,Joint>();
      for (Map.Entry<JointType, Joint> other_element : other.joints.entrySet()) {

        JointType other_element_key = other_element.getKey();
        Joint other_element_value = other_element.getValue();

        JointType __this__joints_copy_key = other_element_key;

        Joint __this__joints_copy_value = new Joint(other_element_value);

        __this__joints.put(__this__joints_copy_key, __this__joints_copy_value);
      }
      this.joints = __this__joints;
    }
    if (other.isSetWords()) {
      Set<String> __this__words = new HashSet<String>();
      for (String other_element : other.words) {
        __this__words.add(other_element);
      }
      this.words = __this__words;
    }
  }

  public Frame deepCopy() {
    return new Frame(this);
  }

  @Override
  public void clear() {
    setFrameIdIsSet(false);
    this.frameId = 0;
    this.image = null;
    this.depthImage = null;
    this.position = null;
    this.joints = null;
    this.words = null;
  }

  public int getFrameId() {
    return this.frameId;
  }

  public Frame setFrameId(int frameId) {
    this.frameId = frameId;
    setFrameIdIsSet(true);
    return this;
  }

  public void unsetFrameId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FRAMEID_ISSET_ID);
  }

  /** Returns true if field frameId is set (has been assigned a value) and false otherwise */
  public boolean isSetFrameId() {
    return EncodingUtils.testBit(__isset_bitfield, __FRAMEID_ISSET_ID);
  }

  public void setFrameIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FRAMEID_ISSET_ID, value);
  }

  public byte[] getImage() {
    setImage(org.apache.thrift.TBaseHelper.rightSize(image));
    return image == null ? null : image.array();
  }

  public ByteBuffer bufferForImage() {
    return image;
  }

  public Frame setImage(byte[] image) {
    setImage(image == null ? (ByteBuffer)null : ByteBuffer.wrap(image));
    return this;
  }

  public Frame setImage(ByteBuffer image) {
    this.image = image;
    return this;
  }

  public void unsetImage() {
    this.image = null;
  }

  /** Returns true if field image is set (has been assigned a value) and false otherwise */
  public boolean isSetImage() {
    return this.image != null;
  }

  public void setImageIsSet(boolean value) {
    if (!value) {
      this.image = null;
    }
  }

  public byte[] getDepthImage() {
    setDepthImage(org.apache.thrift.TBaseHelper.rightSize(depthImage));
    return depthImage == null ? null : depthImage.array();
  }

  public ByteBuffer bufferForDepthImage() {
    return depthImage;
  }

  public Frame setDepthImage(byte[] depthImage) {
    setDepthImage(depthImage == null ? (ByteBuffer)null : ByteBuffer.wrap(depthImage));
    return this;
  }

  public Frame setDepthImage(ByteBuffer depthImage) {
    this.depthImage = depthImage;
    return this;
  }

  public void unsetDepthImage() {
    this.depthImage = null;
  }

  /** Returns true if field depthImage is set (has been assigned a value) and false otherwise */
  public boolean isSetDepthImage() {
    return this.depthImage != null;
  }

  public void setDepthImageIsSet(boolean value) {
    if (!value) {
      this.depthImage = null;
    }
  }

  public Position3D getPosition() {
    return this.position;
  }

  public Frame setPosition(Position3D position) {
    this.position = position;
    return this;
  }

  public void unsetPosition() {
    this.position = null;
  }

  /** Returns true if field position is set (has been assigned a value) and false otherwise */
  public boolean isSetPosition() {
    return this.position != null;
  }

  public void setPositionIsSet(boolean value) {
    if (!value) {
      this.position = null;
    }
  }

  public int getJointsSize() {
    return (this.joints == null) ? 0 : this.joints.size();
  }

  public void putToJoints(JointType key, Joint val) {
    if (this.joints == null) {
      this.joints = new HashMap<JointType,Joint>();
    }
    this.joints.put(key, val);
  }

  public Map<JointType,Joint> getJoints() {
    return this.joints;
  }

  public Frame setJoints(Map<JointType,Joint> joints) {
    this.joints = joints;
    return this;
  }

  public void unsetJoints() {
    this.joints = null;
  }

  /** Returns true if field joints is set (has been assigned a value) and false otherwise */
  public boolean isSetJoints() {
    return this.joints != null;
  }

  public void setJointsIsSet(boolean value) {
    if (!value) {
      this.joints = null;
    }
  }

  public int getWordsSize() {
    return (this.words == null) ? 0 : this.words.size();
  }

  public java.util.Iterator<String> getWordsIterator() {
    return (this.words == null) ? null : this.words.iterator();
  }

  public void addToWords(String elem) {
    if (this.words == null) {
      this.words = new HashSet<String>();
    }
    this.words.add(elem);
  }

  public Set<String> getWords() {
    return this.words;
  }

  public Frame setWords(Set<String> words) {
    this.words = words;
    return this;
  }

  public void unsetWords() {
    this.words = null;
  }

  /** Returns true if field words is set (has been assigned a value) and false otherwise */
  public boolean isSetWords() {
    return this.words != null;
  }

  public void setWordsIsSet(boolean value) {
    if (!value) {
      this.words = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FRAME_ID:
      if (value == null) {
        unsetFrameId();
      } else {
        setFrameId((Integer)value);
      }
      break;

    case IMAGE:
      if (value == null) {
        unsetImage();
      } else {
        setImage((ByteBuffer)value);
      }
      break;

    case DEPTH_IMAGE:
      if (value == null) {
        unsetDepthImage();
      } else {
        setDepthImage((ByteBuffer)value);
      }
      break;

    case POSITION:
      if (value == null) {
        unsetPosition();
      } else {
        setPosition((Position3D)value);
      }
      break;

    case JOINTS:
      if (value == null) {
        unsetJoints();
      } else {
        setJoints((Map<JointType,Joint>)value);
      }
      break;

    case WORDS:
      if (value == null) {
        unsetWords();
      } else {
        setWords((Set<String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FRAME_ID:
      return Integer.valueOf(getFrameId());

    case IMAGE:
      return getImage();

    case DEPTH_IMAGE:
      return getDepthImage();

    case POSITION:
      return getPosition();

    case JOINTS:
      return getJoints();

    case WORDS:
      return getWords();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FRAME_ID:
      return isSetFrameId();
    case IMAGE:
      return isSetImage();
    case DEPTH_IMAGE:
      return isSetDepthImage();
    case POSITION:
      return isSetPosition();
    case JOINTS:
      return isSetJoints();
    case WORDS:
      return isSetWords();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Frame)
      return this.equals((Frame)that);
    return false;
  }

  public boolean equals(Frame that) {
    if (that == null)
      return false;

    boolean this_present_frameId = true;
    boolean that_present_frameId = true;
    if (this_present_frameId || that_present_frameId) {
      if (!(this_present_frameId && that_present_frameId))
        return false;
      if (this.frameId != that.frameId)
        return false;
    }

    boolean this_present_image = true && this.isSetImage();
    boolean that_present_image = true && that.isSetImage();
    if (this_present_image || that_present_image) {
      if (!(this_present_image && that_present_image))
        return false;
      if (!this.image.equals(that.image))
        return false;
    }

    boolean this_present_depthImage = true && this.isSetDepthImage();
    boolean that_present_depthImage = true && that.isSetDepthImage();
    if (this_present_depthImage || that_present_depthImage) {
      if (!(this_present_depthImage && that_present_depthImage))
        return false;
      if (!this.depthImage.equals(that.depthImage))
        return false;
    }

    boolean this_present_position = true && this.isSetPosition();
    boolean that_present_position = true && that.isSetPosition();
    if (this_present_position || that_present_position) {
      if (!(this_present_position && that_present_position))
        return false;
      if (!this.position.equals(that.position))
        return false;
    }

    boolean this_present_joints = true && this.isSetJoints();
    boolean that_present_joints = true && that.isSetJoints();
    if (this_present_joints || that_present_joints) {
      if (!(this_present_joints && that_present_joints))
        return false;
      if (!this.joints.equals(that.joints))
        return false;
    }

    boolean this_present_words = true && this.isSetWords();
    boolean that_present_words = true && that.isSetWords();
    if (this_present_words || that_present_words) {
      if (!(this_present_words && that_present_words))
        return false;
      if (!this.words.equals(that.words))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(Frame other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    Frame typedOther = (Frame)other;

    lastComparison = Boolean.valueOf(isSetFrameId()).compareTo(typedOther.isSetFrameId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFrameId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.frameId, typedOther.frameId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetImage()).compareTo(typedOther.isSetImage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.image, typedOther.image);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDepthImage()).compareTo(typedOther.isSetDepthImage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDepthImage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.depthImage, typedOther.depthImage);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPosition()).compareTo(typedOther.isSetPosition());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPosition()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.position, typedOther.position);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetJoints()).compareTo(typedOther.isSetJoints());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetJoints()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.joints, typedOther.joints);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetWords()).compareTo(typedOther.isSetWords());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWords()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.words, typedOther.words);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Frame(");
    boolean first = true;

    sb.append("frameId:");
    sb.append(this.frameId);
    first = false;
    if (isSetImage()) {
      if (!first) sb.append(", ");
      sb.append("image:");
      if (this.image == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.image, sb);
      }
      first = false;
    }
    if (isSetDepthImage()) {
      if (!first) sb.append(", ");
      sb.append("depthImage:");
      if (this.depthImage == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.depthImage, sb);
      }
      first = false;
    }
    if (isSetPosition()) {
      if (!first) sb.append(", ");
      sb.append("position:");
      if (this.position == null) {
        sb.append("null");
      } else {
        sb.append(this.position);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("joints:");
    if (this.joints == null) {
      sb.append("null");
    } else {
      sb.append(this.joints);
    }
    first = false;
    if (isSetWords()) {
      if (!first) sb.append(", ");
      sb.append("words:");
      if (this.words == null) {
        sb.append("null");
      } else {
        sb.append(this.words);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'frameId' because it's a primitive and you chose the non-beans generator.
    if (joints == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'joints' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (position != null) {
      position.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FrameStandardSchemeFactory implements SchemeFactory {
    public FrameStandardScheme getScheme() {
      return new FrameStandardScheme();
    }
  }

  private static class FrameStandardScheme extends StandardScheme<Frame> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Frame struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FRAME_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.frameId = iprot.readI32();
              struct.setFrameIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // IMAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.image = iprot.readBinary();
              struct.setImageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DEPTH_IMAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.depthImage = iprot.readBinary();
              struct.setDepthImageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // POSITION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.position = new Position3D();
              struct.position.read(iprot);
              struct.setPositionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // JOINTS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                struct.joints = new HashMap<JointType,Joint>(2*_map0.size);
                for (int _i1 = 0; _i1 < _map0.size; ++_i1)
                {
                  JointType _key2; // required
                  Joint _val3; // required
                  _key2 = JointType.findByValue(iprot.readI32());
                  _val3 = new Joint();
                  _val3.read(iprot);
                  struct.joints.put(_key2, _val3);
                }
                iprot.readMapEnd();
              }
              struct.setJointsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // WORDS
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set4 = iprot.readSetBegin();
                struct.words = new HashSet<String>(2*_set4.size);
                for (int _i5 = 0; _i5 < _set4.size; ++_i5)
                {
                  String _elem6; // required
                  _elem6 = iprot.readString();
                  struct.words.add(_elem6);
                }
                iprot.readSetEnd();
              }
              struct.setWordsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetFrameId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'frameId' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Frame struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(FRAME_ID_FIELD_DESC);
      oprot.writeI32(struct.frameId);
      oprot.writeFieldEnd();
      if (struct.image != null) {
        if (struct.isSetImage()) {
          oprot.writeFieldBegin(IMAGE_FIELD_DESC);
          oprot.writeBinary(struct.image);
          oprot.writeFieldEnd();
        }
      }
      if (struct.depthImage != null) {
        if (struct.isSetDepthImage()) {
          oprot.writeFieldBegin(DEPTH_IMAGE_FIELD_DESC);
          oprot.writeBinary(struct.depthImage);
          oprot.writeFieldEnd();
        }
      }
      if (struct.position != null) {
        if (struct.isSetPosition()) {
          oprot.writeFieldBegin(POSITION_FIELD_DESC);
          struct.position.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.joints != null) {
        oprot.writeFieldBegin(JOINTS_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.STRUCT, struct.joints.size()));
          for (Map.Entry<JointType, Joint> _iter7 : struct.joints.entrySet())
          {
            oprot.writeI32(_iter7.getKey().getValue());
            _iter7.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.words != null) {
        if (struct.isSetWords()) {
          oprot.writeFieldBegin(WORDS_FIELD_DESC);
          {
            oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRING, struct.words.size()));
            for (String _iter8 : struct.words)
            {
              oprot.writeString(_iter8);
            }
            oprot.writeSetEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FrameTupleSchemeFactory implements SchemeFactory {
    public FrameTupleScheme getScheme() {
      return new FrameTupleScheme();
    }
  }

  private static class FrameTupleScheme extends TupleScheme<Frame> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Frame struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.frameId);
      {
        oprot.writeI32(struct.joints.size());
        for (Map.Entry<JointType, Joint> _iter9 : struct.joints.entrySet())
        {
          oprot.writeI32(_iter9.getKey().getValue());
          _iter9.getValue().write(oprot);
        }
      }
      BitSet optionals = new BitSet();
      if (struct.isSetImage()) {
        optionals.set(0);
      }
      if (struct.isSetDepthImage()) {
        optionals.set(1);
      }
      if (struct.isSetPosition()) {
        optionals.set(2);
      }
      if (struct.isSetWords()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetImage()) {
        oprot.writeBinary(struct.image);
      }
      if (struct.isSetDepthImage()) {
        oprot.writeBinary(struct.depthImage);
      }
      if (struct.isSetPosition()) {
        struct.position.write(oprot);
      }
      if (struct.isSetWords()) {
        {
          oprot.writeI32(struct.words.size());
          for (String _iter10 : struct.words)
          {
            oprot.writeString(_iter10);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Frame struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.frameId = iprot.readI32();
      struct.setFrameIdIsSet(true);
      {
        org.apache.thrift.protocol.TMap _map11 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.joints = new HashMap<JointType,Joint>(2*_map11.size);
        for (int _i12 = 0; _i12 < _map11.size; ++_i12)
        {
          JointType _key13; // required
          Joint _val14; // required
          _key13 = JointType.findByValue(iprot.readI32());
          _val14 = new Joint();
          _val14.read(iprot);
          struct.joints.put(_key13, _val14);
        }
      }
      struct.setJointsIsSet(true);
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.image = iprot.readBinary();
        struct.setImageIsSet(true);
      }
      if (incoming.get(1)) {
        struct.depthImage = iprot.readBinary();
        struct.setDepthImageIsSet(true);
      }
      if (incoming.get(2)) {
        struct.position = new Position3D();
        struct.position.read(iprot);
        struct.setPositionIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TSet _set15 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.words = new HashSet<String>(2*_set15.size);
          for (int _i16 = 0; _i16 < _set15.size; ++_i16)
          {
            String _elem17; // required
            _elem17 = iprot.readString();
            struct.words.add(_elem17);
          }
        }
        struct.setWordsIsSet(true);
      }
    }
  }

}

