/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Jp.Digitalmuseum.Kinect
{
  public enum JointType
  {
    HIP_CENTER = 0,
    SPINE = 1,
    SHOULDER_CENTER = 2,
    HEAD = 3,
    SHOULDER_RIGHT = 4,
    ELBOW_RIGHT = 5,
    WRIST_RIGHT = 6,
    HAND_RIGHT = 7,
    SHOULDER_LEFT = 8,
    ELBOW_LEFT = 9,
    WRIST_LEFT = 10,
    HAND_LEFT = 11,
    HIP_RIGHT = 12,
    KNEE_RIGHT = 13,
    ANKLE_RIGHT = 14,
    FOOT_RIGHT = 15,
    HIP_LEFT = 16,
    KNEE_LEFT = 17,
    ANKLE_LEFT = 18,
    FOOT_LEFT = 19,
  }
}
